server:
  port: 9090
  servlet:
    context-path: /TCU/V1

# 数据源配置
spring:
  datasource:
    username: root
    password: ndwmd1230
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8&allowMultiQueries=true

  #GMT%2b8
  security:
    user:
      name: admin
      password: admin
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        min-idle: 0
        max-wait: -1s
        max-idle: 8
    lettuce:
      shutdown-timeout: 100ms
    timeout: 8000
  cache:
    type: redis
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

mybatis-plus:
  global-config:
    db-config:
      id-type: auto

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl




